name: Update Landscape from LFX
description: Update the given landscape from LFx
inputs:
  project_processing:
    description: "Indicate for project processing, if they should be 'rebuild' or 'sync' ( or 'skip' to not build projects )"
    default: "sync"
runs:
  using: composite
  steps:
    - name: Install cairo
      shell: bash
      run: sudo apt install libcairo2-dev
    - name: Checkout landscape
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7@v4
      with:
        token: ${{ env.token }}
        repository: ${{ env.repository }}
        ref: ${{ env.ref }}
        path: landscape
    - name: Checkout landscape-tools
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7@v4
      with:
        token: ${{ env.token }}
        repository: jmertic/lfx-landscape-tools
        path: landscape-tools
    - name: Set up Python 3.x
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.x'
    - name: Install poetry
      uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # v3.0.0
    - name: Install dependencies
      shell: bash
      working-directory: ./landscape-tools
      run: poetry install
    - name: Build members from LFX
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape build_members -c ../landscape/config.yml
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
    - name: Rebuild projects from LFX and other sources
      if: ${{ inputs.project_processing == 'rebuild' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape build_projects -c ../landscape/config.yml
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
    - name: Sync projects from LFX and other sources
      if: ${{ inputs.project_processing == 'sync' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run landscape sync_projects -c ../landscape/config.yml
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
    - name: Save missing.csv file
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: missing-members 
        path: ./landscape/missing.csv
    - name: Validate landscape2 data
      uses: cncf/landscape2-validate-action@7f299c46e9b03b4e8bc2896882734fb0b0756b37 # v2.0.0
      with:
        target_kind: data
        target_path: ./landscape/landscape.yml
    - name: Checkout landscapeapp
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7@v4
      with:
        repository: cncf/landscapeapp
        path: landscapeapp
    - name: Setup node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '18'
    - name: Cleanup YAML files
      working-directory: ./landscapeapp
      shell: bash
      run: |
        node tools/removePuppeteer
        npm install
        PROJECT_PATH=../landscape node tools/removeQuotes
        PROJECT_PATH=../landscape node tools/pruneExtraEntries
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
      with:
        format: "YYYY-MM-DD"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        token: ${{ env.token }}
        branch-suffix: timestamp
        path: ./landscape
        title: "Update Landscape from LFX ${{ steps.date.outputs.time }}"
        labels: automated-build
        commit-message: Update Landscape from LFX
        signoff: true

